version: '3'
services:
 db:
    image: mysql:5.7
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
  
 app:
    build: .
    volumes:
      - ./myapp:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    depends_on:
      - db
 
 web:
    build: nginx
    ports:
      - "8080:80"
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    depends_on:
      - app

volumes:
  public-data:
  tmp-data:
  log-data:
